.TH V "1" "February 2011" "v" "User Commands"

.SH NAME
v \- z for vim

.SH SYNOPSIS
v [\-a] [\-l] [\-[0\-9]] [\-\-debug] [\-\-help] [regex1 regex2 ... regexn]

.SH AVAILABILITY
bash, vim

.SH DESCRIPTION
\fBv\fR uses viminfo's list of recently edited files to open one quickly no
matter where you are in the filesystem.
.P
By default, it will open the most recently edited file matching all of the
provided regular expressions.

.SH OPTIONS
\fB\-a\fR        don't skip deleted files
.br
\fB\-l\fR        when multiple matches, show a list
.br
\fB\-[0\-9]\fR    edit nth most recent file
.br
\fB\--debug\fR   dry run
.br
\fB\--help\fR    show a brief help message

.SH EXAMPLES
\fBv\fR         list all files
.br
\fBv -1\fR      reopen most recently edited file
.br
\fBv foo bar\fR edit file matching foo and bar.

.SH NOTES
Shell variables, such as $, must be escaped if used in regular expressions.

You may find it useful to alias vl='v -l'

.SH SEE ALSO
vim(1), regex(7)
.P
Please file bugs at https://github.com/rupa/v/
