.TH V "1" "February 2011" "v" "User Commands"

.SH NAME
v \- z for vim

.SH SYNOPSIS
v [\-a] [\-c] [\-l] [\-[0\-9]] [\-\-debug] [\-\-help] [regex1 regex2 ... regexn]

.SH AVAILABILITY
bash, vim

.SH INSTALLATION
Put \fBv\fR somewhere in $PATH (e.g. /usr/local/bin/).
.br
For the manual page, put \fBv.1\fR somewhere in $MANPATH (e.g.
/usr/local/man/man1/).

.SH DESCRIPTION
\fBv\fR uses viminfo's list of recently edited files to open one quickly no
matter where you are in the filesystem.
.P
By default, it will open the most recently edited file matching all of the
provided regular expressions.

.SH OPTIONS
\fB\-a\fR           don't skip deleted files
.br
\fB\-c\fR           restrict matches to subdirectories of the current dir
.br
\fB\-l\fR           when multiple matches, show a list
.br
\fB\-[0\-9]\fR       edit nth most recent file
.br
\fB\--debug\fR      dry run
.br
\fB\--help\fR       show a brief help message

.SH EXAMPLES
\fBv\fR            list and choose from all files
.br
\fBv -0\fR         reopen most recently edited file
.br
\fBv foo bar\fR    edit first file matching foo and bar
.br
\fBv -c foo bar\fR choose files in current dir matching foo and bar
.br
\fBv -l foo bar\fR list and choose files matching foo and bar

.SH NOTES
Shell variables, such as $, must be escaped if used in regular expressions.

\fBBehavior\fR
.br
The default behavior is to open the most recent file that matches the search
terms, even if there are multiple matches.

You may find it useful to alias vl='v -l'. When there are multiple matches,
this will prompt for a choice, rather than editing the first match. The author
is still not sure which behavior should be the default, and has chosen one 
provisionally.

.SH SEE ALSO
vim(1), regex(7)
.P
Please file bugs at https://github.com/rupa/v/
